-- 코드를 입력하세요
# SELECT A.AUTHOR_ID,A.AUTHOR_NAME,BS.CATEGORY,SUM(BS.TOTAL_SALES) AS TOTAL_SALES
# FROM 
# (SELECT B.BOOK_ID, SUM(S.SALES)*B.PRICE AS TOTAL_SALES,B.CATEGORY,B.AUTHOR_ID FROM BOOK_SALES S 
# JOIN BOOK B ON S.BOOK_ID=B.BOOK_ID 
# WHERE DATE_FORMAT(S.SALES_DATE,"%Y-%d")="2022-01"
# GROUP BY B.BOOK_ID) BS 
# JOIN AUTHOR A ON BS.AUTHOR_ID = A.AUTHOR_ID
# GROUP BY BS.AUTHOR_ID,BS.CATEGORY
# ORDER BY AUTHOR_ID ASC,CATEGORY DESC;


SELECT A.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY,SUM(S.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
# WHERE DATE_FORMAT(S.SALES_DATE,"%Y-%d")="2022-01"
WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.AUTHOR_ID,B.CATEGORY
ORDER BY AUTHOR_ID ASC,CATEGORY DESC;