-- 코드를 입력하세요
SELECT C.CAR_ID,C.CAR_TYPE
,(C.DAILY_FEE*30)-(C.DAILY_FEE*30)
*(REPLACE(
    (SELECT DISCOUNT_RATE 
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
     WHERE P.CAR_TYPE=C.CAR_TYPE AND P.DURATION_TYPE REGEXP("30")),"%","")/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C 
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE ="세단" OR C.CAR_TYPE ="SUV"
GROUP BY C.CAR_ID
HAVING COUNT(CASE 
             WHEN DATE_FORMAT(H.END_DATE,"%Y-%m") <= "2022-10" THEN 1
             ELSE NULL
             END) +
       COUNT(CASE 
             WHEN DATE_FORMAT(H.START_DATE,"%Y-%m") >= "2022-12" THEN 1
             ELSE NULL
             END) = COUNT(H.START_DATE)
        AND FEE >=500000 AND FEE<2000000
ORDER BY FEE DESC, CAR_TYPE,CAR_ID;
             
# SELECT * FROM CAR_RENTAL_COMPANY_CAR
             

