-- 코드를 입력하세요
SELECT R.FOOD_TYPE,R.REST_ID,R.REST_NAME,R.FAVORITES
FROM REST_INFO R
WHERE R.FAVORITES = 
(SELECT MAX(R1.FAVORITES) FROM REST_INFO R1 WHERE R1.FOOD_TYPE=R.FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;