-- 코드를 입력하세요
# SELECT DATE_FORMAT(S.SALES_DATE,"%Y"), DATE_FORMAT(S.SALES_DATE,"%d"), I.GENDER
# ,COUNT((SELECT DISTINCT I1.USER_ID 
#         FROM ONLINE_SALE S1 JOIN USER_INFO I1 ON S1.USER_ID = I1.USER_ID
#         WHERE DATE_FORMAT(S1.SALES_DATE,"%Y")=DATE_FORMAT(S.SALES_DATE,"%Y")
#         AND DATE_FORMAT(S1.SALES_DATE,"%d")=DATE_FORMAT(S.SALES_DATE,"%d")
#         AND I.GENDER = I1.GENDER))
# FROM USER_INFO I JOIN ONLINE_SALE S ON I.USER_ID=S.USER_ID
# WHERE I.GENDER IS NOT NULL
# GROUP BY DATE_FORMAT(S.SALES_DATE,"%Y"), DATE_FORMAT(S.SALES_DATE,"%d"), I.GENDER

SELECT DATE_FORMAT(S.SALES_DATE,"%Y") AS YEAR
, CAST(DATE_FORMAT(S.SALES_DATE,"%m") AS UNSIGNED) AS MONTH
, I.GENDER AS GENDER
,COUNT(DISTINCT I.USER_ID) AS USERS
FROM USER_INFO I JOIN ONLINE_SALE S ON I.USER_ID=S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY DATE_FORMAT(S.SALES_DATE,"%Y"), DATE_FORMAT(S.SALES_DATE,"%m"), I.GENDER