-- 코드를 입력하세요
SELECT CAR_TYPE, COUNT(*) AS "CARS" FROM CAR_RENTAL_COMPANY_CAR C 
WHERE C.OPTIONS REGEXP("통풍시트|열선시트|가죽시트")
GROUP BY C.CAR_TYPE
ORDER BY C.CAR_TYPE

# SELECT * FROM CAR_RENTAL_COMPANY_CAR

