-- 코드를 입력하세요
SELECT CARS.CAR_ID, (CASE 
        WHEN EXISTS(SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY TR WHERE START_DATE<="2022-10-16" AND END_DATE>="2022-10-16" AND CARS.CAR_ID=TR.CAR_ID) THEN "대여중"
        ELSE "대여 가능" END) AS AVAILABILITY
FROM (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) CARS
ORDER BY CAR_ID DESC;

# SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE<="2022-10-16" AND END_DATE>="2022-10-16" ORDER BY CAR_ID;

# BETWEEN START_DATE AND END_DATE

# SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY ORDER BY CAR_ID