-- 코드를 입력하세요
WITH RECURSIVE HOUR(N) AS(
    SELECT 0
    UNION ALL
    SELECT N+1 FROM HOUR WHERE N<23
)

SELECT H.N  AS HOUR ,COUNT(O.ANIMAL_ID) AS COUNT
FROM HOUR H 
LEFT JOIN ANIMAL_OUTS O 
ON H.N = CAST(DATE_FORMAT(O.DATETIME,"%H") AS UNSIGNED) 
GROUP BY H.N
ORDER BY HOUR;
