-- 코드를 작성해주세요

SELECT E.EMP_NO,E.EMP_NAME,
(
    CASE
    WHEN AVG(G.SCORE) >= 96 THEN "S"
    WHEN AVG(G.SCORE) >= 90 THEN "A"
    WHEN AVG(G.SCORE) >= 80 THEN "B"
    ELSE "C"
    END
) AS GRADE,
(
    CASE
    WHEN AVG(G.SCORE) >= 96 THEN TRUNCATE(E.SAL*0.2,0)
    WHEN AVG(G.SCORE) >= 90 THEN TRUNCATE(E.SAL*0.15,0)
    WHEN AVG(G.SCORE) >= 80 THEN TRUNCATE(E.SAL*0.1,0)
    ELSE 0
    END
) AS BONUS
FROM HR_EMPLOYEES E JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
ORDER BY EMP_NO