-- 코드를 입력하세요
WITH REVIEW_COUNT AS(
    SELECT M.MEMBER_ID,M.MEMBER_NAME,M.TLNO,COUNT(*) AS R_COUNT
    FROM MEMBER_PROFILE M 
    JOIN REST_REVIEW R ON M.MEMBER_ID=R.MEMBER_ID
    GROUP BY M.MEMBER_ID
    ORDER BY R_COUNT DESC
    LIMIT 1
)
SELECT C.MEMBER_NAME,R.REVIEW_TEXT,DATE_FORMAT(R.REVIEW_DATE,"%Y-%m-%d")
FROM REVIEW_COUNT C 
JOIN REST_REVIEW R ON C.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE,REVIEW_TEXT;