-- 코드를 작성해주세요
SELECT SUM(HG.SCORE) AS "SCORE", HG.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL 
FROM HR_GRADE HG
JOIN HR_EMPLOYEES HE ON HG.EMP_NO = HE.EMP_NO
GROUP BY HG.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;

# SELECT * FROM HR_GRADE ORDER BY SCORE DESC
# SELECT * FROM HR_GRADE 