-- 코드를 입력하세요
WITH ORDER_IN_CATEGORY AS(
    SELECT 
    F.CATEGORY,
    F.PRICE,
    F.PRODUCT_NAME,
    MAX(F.PRICE)
    OVER(PARTITION BY F.CATEGORY ORDER BY F.PRICE DESC 
         ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS MAX_PRICE
    FROM FOOD_PRODUCT F 
    WHERE F.CATEGORY IN ("과자","국","김치","식용유")
)


SELECT CATEGORY,MAX_PRICE,PRODUCT_NAME FROM ORDER_IN_CATEGORY WHERE PRICE=MAX_PRICE
ORDER BY MAX_PRICE DESC;
