-- 코드를 작성해주세요
SELECT
(
    CASE
    WHEN GROUP_CONCAT(S.NAME) REGEXP(".*Python.*") AND GROUP_CONCAT(S.CATEGORY) REGEXP(".*FRONT END.*")
    THEN "A"
    WHEN GROUP_CONCAT(S.NAME) REGEXP(".*C#.*") 
    THEN "B"
    WHEN GROUP_CONCAT(S.CATEGORY) REGEXP(".*FRONT END.*") 
    THEN "C"
    ELSE "N"
    END
) AS GRADE ,D.ID,D.EMAIL
FROM DEVELOPERS D 
JOIN SKILLCODES S ON D.SKILL_CODE&S.CODE!=0
GROUP BY D.ID,D.EMAIL
HAVING GRADE!="N"
ORDER BY GRADE,ID;