-- 코드를 작성해주세요
WITH SKILLS AS(
    SELECT *
    FROM DEVELOPERS D
    JOIN SKILLCODES S ON (D.SKILL_CODE&S.CODE)!=0
)

SELECT * FROM(
    SELECT 
(CASE
WHEN A.FRONT_COUNT !=0 AND A.PYTHON_COUNT!=0 THEN "A"
WHEN A.C_COUNT !=0 THEN "B"
WHEN A.FRONT_COUNT !=0 THEN "C"
ELSE "N"
END) AS GRADE,
A.ID,A.EMAIL FROM
(
    SELECT *
    ,(SELECT COUNT(*) FROM SKILLS S WHERE S.CATEGORY='FRONT END' AND D.ID=S.ID) AS FRONT_COUNT
    ,(SELECT COUNT(*) FROM SKILLS S WHERE S.NAME='Python' AND D.ID=S.ID) PYTHON_COUNT
    ,(SELECT COUNT(*) FROM SKILLS S WHERE S.NAME='C#' AND D.ID=S.ID) C_COUNT
    FROM DEVELOPERS D
) A
) B WHERE B.GRADE!="N" ORDER BY B.GRADE,B.ID;

